-- MySQL Script generated by MySQL Workbench
-- ven. 04 déc. 2015 00:20:35 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `captation` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `captation` ;

-- -----------------------------------------------------
-- Table `mydb`.`Geolocalizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captation`.`Geolocalizations` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `latitude` DOUBLE NOT NULL COMMENT '',
  `longitude` DOUBLE NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captation`.`Users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `is_wounded` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `is_in_danger` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `Geolocalizations_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `Geolocalizations_id`)  COMMENT '',
  INDEX `fk_Users_Geolocalizations1_idx` (`Geolocalizations_id` ASC)  COMMENT '',
  CONSTRAINT `fk_Users_Geolocalizations1`
    FOREIGN KEY (`Geolocalizations_id`)
    REFERENCES `mydb`.`Geolocalizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Organisations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captation`.`Organisations` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(255) NOT NULL COMMENT '',
  `mail` VARCHAR(255) NOT NULL COMMENT '',
  `tel` NVARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Locale_structures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captation`.`Locale_structures` (
  `Organisations_id` INT NOT NULL COMMENT '',
  `tel` NVARCHAR(15) NOT NULL COMMENT '',
  `mail` VARCHAR(255) NOT NULL COMMENT '',
  `Geolocalizations_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`Organisations_id`, `Geolocalizations_id`)  COMMENT '',
  INDEX `fk_Locale_structures_Geolocalizations1_idx` (`Geolocalizations_id` ASC)  COMMENT '',
  CONSTRAINT `fk_table1_Organisation`
    FOREIGN KEY (`Organisations_id`)
    REFERENCES `mydb`.`Organisations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Locale_structures_Geolocalizations1`
    FOREIGN KEY (`Geolocalizations_id`)
    REFERENCES `mydb`.`Geolocalizations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `captation`.`Events` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` NVARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
